In [50]:
from pandas import read_csv

In [51]:
data = read_csv('cars.csv')

In [52]:
data.isna().sum()

mpg             0
 cylinders      0
 cubicinches    0
 hp             0
 weightlbs      0
 time-to-60     0
 year           0
 brand          0
dtype: int64

In [53]:
data.fillna(data.mean(), inplace=True)

In [54]:
list(data)

['mpg',
 ' cylinders',
 ' cubicinches',
 ' hp',
 ' weightlbs',
 ' time-to-60',
 ' year',
 ' brand']

In [55]:
from sklearn.preprocessing import LabelEncoder

In [56]:
labelEncoder = LabelEncoder()

In [57]:
labelEncoder.fit(data[' brand'])

LabelEncoder()

In [58]:
data[' brand'] = labelEncoder.transform(data[' brand'])

In [59]:
data.head(45)

mpg   cylinders  cubicinches   hp  weightlbs   time-to-60   year   brand
0   14.0           8          350  165       4209           12   1972       2
1   31.9           4           89   71       1925           14   1980       0
2   17.0           8          302  140       3449           11   1971       2
3   15.0           8          400  150       3761           10   1971       2
4   30.5           4           98   63       2051           17   1978       2
5   23.0           8          350  125       3900           17   1980       2
6   13.0           8          351  158       4363           13   1974       2
7   14.0           8          440  215       4312            9   1971       2
8   25.4           5          183   77       3530           20   1980       0
9   37.7           4           89   62       2050           17   1982       1
10  34.0           4          108   70       2245           17   1983       1
11  34.3           4           97   78       2188           16   1981       0
12  16.0           8          302  140       4141           14   1975       2
13  11.0           8          350  180       3664           11   1974       2
14  19.1           6          225   90                      19   1981       2
15  16.9           8          350  155       4360           15   1980       2
16  31.8           4           85   65       2020           19   1980       1
17  16.0           8          304  150       3433           12   1971       2
18  24.0           4          113   95       2278           16   1973       1
19  24.0           4          107   90       2430           15   1971       0
20  37.2           4           86   65       2019           16   1981       1
21  21.5           4          121  110       2600           13   1978       0
22  24.0           6          200   81       3012           18   1977       2
23  15.5           8          351  142       4054           14   1980       2
24  38.1           4           89   60       1968           19   1981       1
25  33.0           4           91   53       1795           17   1977       1
26  31.0           4           71   65       1773           19   1972       1
27  14.0           8          351  148       4657           14   1976       2
28  18.0           6          250   78       3574           21   1977       2
29  29.9           4           98   65       2380           21   1982       2
30  27.0           4           97   88       2130           15   1971       1
31  16.0           6          250  100       3278           18   1974       2
32  23.0           4          120   97       2506           15   1973       1
33  21.0           6          199   90                      15   1971       2
34  30.0           4           97   67       1985           16   1978       1
35  22.4           6          231  110       3415           16   1982       2
36  26.0           4           97   46       1835           21   1971       0
37  21.5           3           80  110       2720           14   1978       1
38  16.5           8          351  138       3955           13   1980       2
39  20.2           6          232   90       3265           18   1980       2
40  16.0           6               105       3897           19   1976       2
41  14.0           8          302  140       4638           16   1975       2
42  18.5           6          250  110       3645           16   1977       2
43  17.5           6          250  110       3520           16   1978       2
44  14.0           8          455  225       3086           10   1971       2

In [60]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 261 entries, 0 to 260
Data columns (total 8 columns):
mpg             261 non-null float64
 cylinders      261 non-null int64
 cubicinches    261 non-null object
 hp             261 non-null int64
 weightlbs      261 non-null object
 time-to-60     261 non-null int64
 year           261 non-null int64
 brand          261 non-null int32
dtypes: float64(1), int32(1), int64(4), object(2)
memory usage: 15.4+ KB


In [61]:
data[' cubicinches'].head(45)

0     350
1      89
2     302
3     400
4      98
5     350
6     351
7     440
8     183
9      89
10    108
11     97
12    302
13    350
14    225
15    350
16     85
17    304
18    113
19    107
20     86
21    121
22    200
23    351
24     89
25     91
26     71
27    351
28    250
29     98
30     97
31    250
32    120
33    199
34     97
35    231
36     97
37     80
38    351
39    232
40       
41    302
42    250
43    250
44    455
Name:  cubicinches, dtype: object

In [62]:
import pandas as pd
data[' cubicinches'] = pd.to_numeric(data[' cubicinches'], errors='coerce')
data[' weightlbs'] = pd.to_numeric(data[' weightlbs'], errors='coerce')

In [63]:
data[' weightlbs'].head(45)

0     4209.0
1     1925.0
2     3449.0
3     3761.0
4     2051.0
5     3900.0
6     4363.0
7     4312.0
8     3530.0
9     2050.0
10    2245.0
11    2188.0
12    4141.0
13    3664.0
14       NaN
15    4360.0
16    2020.0
17    3433.0
18    2278.0
19    2430.0
20    2019.0
21    2600.0
22    3012.0
23    4054.0
24    1968.0
25    1795.0
26    1773.0
27    4657.0
28    3574.0
29    2380.0
30    2130.0
31    3278.0
32    2506.0
33       NaN
34    1985.0
35    3415.0
36    1835.0
37    2720.0
38    3955.0
39    3265.0
40    3897.0
41    4638.0
42    3645.0
43    3520.0
44    3086.0
Name:  weightlbs, dtype: float64

In [64]:
data.fillna(data.mean(), inplace=True)

In [65]:
data.isna().sum()

mpg             0
 cylinders      0
 cubicinches    0
 hp             0
 weightlbs      0
 time-to-60     0
 year           0
 brand          0
dtype: int64

In [66]:
import numpy as np

In [67]:
x = np.array(data.drop(columns = [' brand'], inplace = False))

In [68]:
x

array([[1.400e+01, 8.000e+00, 3.500e+02, ..., 4.209e+03, 1.200e+01,
        1.972e+03],
       [3.190e+01, 4.000e+00, 8.900e+01, ..., 1.925e+03, 1.400e+01,
        1.980e+03],
       [1.700e+01, 8.000e+00, 3.020e+02, ..., 3.449e+03, 1.100e+01,
        1.971e+03],
       ...,
       [2.200e+01, 6.000e+00, 2.320e+02, ..., 2.835e+03, 1.500e+01,
        1.983e+03],
       [1.800e+01, 6.000e+00, 2.320e+02, ..., 3.288e+03, 1.600e+01,
        1.972e+03],
       [2.200e+01, 6.000e+00, 2.500e+02, ..., 3.353e+03, 1.500e+01,
        1.977e+03]])

In [69]:
y = np.array(data[' brand'])

In [70]:
y

array([2, 0, 2, 2, 2, 2, 2, 2, 0, 1, 1, 0, 2, 2, 2, 2, 1, 2, 1, 0, 1, 0,
       2, 2, 1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 2, 0, 1, 2, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 0, 2, 2, 0, 2, 0, 2, 2, 1, 2, 0, 2, 2, 1, 1, 1, 2, 2,
       0, 1, 0, 2, 2, 2, 1, 1, 0, 2, 2, 1, 0, 1, 2, 2, 2, 0, 0, 1, 2, 2,
       2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 0, 0, 0, 2,
       1, 0, 2, 1, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 0, 2, 2, 2, 0, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 0, 0, 2, 1, 1, 1, 2, 0, 2, 2, 2, 2, 1, 1, 2, 2,
       0, 2, 1, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 1, 2, 1, 0, 0, 2, 2, 0,
       2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0,
       0, 1, 0, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 1, 0, 2, 1, 1, 2, 2, 2,
       2, 0, 2, 0, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2,
       2, 0, 2, 2, 2, 0, 1, 2, 2, 0, 0, 2, 2, 1, 2, 1, 2, 2, 2])

In [71]:
from sklearn.cluster import KMeans

In [72]:
kmeans = KMeans(n_clusters=3)
kmeans.fit(x)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [73]:
kmeans.predict([x[0]])

array([1])

In [74]:
y[0]

2

In [75]:
from sklearn.metrics import accuracy_score

In [76]:
accuracy_score(y, kmeans.predict(x))

0.3793103448275862

In [77]:
from sklearn.preprocessing import MinMaxScaler

In [78]:
scaler = MinMaxScaler()

In [103]:
x_scaled = scaler.fit_transform(x)

In [104]:
kmeans.fit(x_scaled)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [105]:
kmeans.predict(x_scaled)

array([2, 1, 2, 2, 1, 2, 2, 2, 0, 1, 1, 1, 2, 2, 0, 2, 1, 2, 1, 1, 1, 1,
       0, 2, 1, 1, 1, 2, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 2, 0, 0, 2, 0, 0,
       2, 1, 2, 1, 1, 0, 2, 1, 2, 1, 2, 2, 0, 1, 1, 2, 0, 1, 0, 1, 2, 0,
       1, 1, 1, 2, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 2, 2, 2, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 2, 0, 1, 0, 2, 0, 2, 0, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 2, 1, 1, 0, 1, 0, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1,
       2, 2, 2, 2, 1, 2, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 2, 2, 1, 1, 2, 0,
       1, 0, 1, 1, 0, 0, 1, 2, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       2, 2, 2, 1, 0, 1, 2, 2, 1, 0, 0, 2, 2, 2, 1, 1, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 2, 1, 0, 2, 0, 0, 0, 1, 1, 0, 1, 1, 2, 0, 2,
       0, 1, 2, 0, 2, 1, 2, 1, 0, 1, 2, 1, 1, 2, 1, 1, 2, 0, 1, 1, 2, 0,
       2, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 0, 1, 2, 1, 0, 0, 0])

In [106]:
accuracy_score(y, kmeans.predict(x_scaled))

0.47126436781609193

In [107]:
import matplotlib.pyplot as plt